FTP
Roenke/java-autumn pull request #4
Opened 2016-10-08 14:10 UTC by Roenke

2016-10-23 19:39 UTC, sproshev requested changes
надо поправить, хотя бы закрытие, тесты, unused

2016-10-23 19:39 UTC, sproshev commented on practice/build.gradle
>      mavenCentral()
насколько я понимаю, jcenter надмножество mavenCentral, т.ч. можно было написать только его

2016-10-23 19:39 UTC, sproshev commented on practice/src/main/java/homework/ftp/client/requests/GetFileRequest.java
> +      }
IOUtils.copy*

2016-10-23 19:39 UTC, sproshev commented on practice/src/main/java/homework/ftp/common/ProtocolDetail.java
> +}
final !!!

2016-10-23 19:39 UTC, sproshev commented on practice/src/main/java/homework/ftp/server/Server.java
> +}
в текущей реализации этот интерфейс выглядит излишним, также как Request

2016-10-23 19:39 UTC, sproshev commented on practice/src/main/java/homework/ftp/server/FtpServer.java
> +        continue;
опасно, clientSocket-то не закрыли

-1

2016-10-23 19:39 UTC, sproshev commented on practice/src/main/java/homework/ftp/server/FtpServer.java
> +        if(clientSocket.isClosed()) {
думаешь это может быть true?

2016-10-23 19:39 UTC, sproshev commented on practice/src/main/java/homework/ftp/server/FtpServer.java
> +        System.err.println("Protocol error: unknown action with id = " + String.valueOf(actionId));
и тут не закрыли

2016-10-23 19:39 UTC, sproshev commented on practice/src/main/java/homework/ftp/server/handlers/Handler.java
> +}
тут тоже похоже на перебор с абстракциями )

2016-10-23 19:39 UTC, sproshev commented on practice/src/main/java/homework/ftp/server/handlers/ListActionHandler.java
> +
сокет не закрывается

2016-10-23 19:39 UTC, sproshev commented on practice/src/main/java/homework/ftp/server/handlers/ex/WrongDataFormatException.java
> +public class WrongDataFormatException extends QueryHandlerException {
unused

2016-10-23 19:39 UTC, sproshev commented on practice/src/main/java/homework/ftp/server/ex/OpenSocketException.java
> +public class OpenSocketException extends ServerException {
unused

2016-10-23 19:39 UTC, sproshev commented on practice/src/test/java/homework/ftp/ListRequestTest.java
> +
и?)

2016-10-23 19:39 UTC, sproshev commented on practice/src/test/java/homework/ftp/RunningServerTestCase.java
> +}
я бы может тестировал клиент через его EntryPoint, но текущий вариант меня устраивает

2016-10-30 17:05 UTC, Roenke commented on practice/src/test/java/homework/ftp/RunningServerTestCase.java
> +}
Так совсем не unit :) сейчас мы хотя бы можем проверить какие исключения прилетают

2016-10-30 17:06 UTC, Roenke commented on practice/src/test/java/homework/ftp/ListRequestTest.java
> +
Что-то я совсем рано решил, что всё готово :( 
дописал

2016-10-30 17:06 UTC, bibaev commented on practice/src/main/java/homework/ftp/server/ex/OpenSocketException.java
> +public class OpenSocketException extends ServerException {
Удалил

2016-10-30 17:06 UTC, Roenke commented on practice/src/main/java/homework/ftp/server/handlers/ex/WrongDataFormatException.java
> +public class WrongDataFormatException extends QueryHandlerException {
Теперь используется, когда не удалось распарсить пути как UTF

2016-10-30 17:06 UTC, Roenke commented on practice/src/main/java/homework/ftp/server/handlers/ListActionHandler.java
> +
пофиксил

2016-10-30 17:06 UTC, Roenke commented on practice/src/main/java/homework/ftp/server/handlers/Handler.java
> +}
все они отличаются исключениями, которые можно бросить

2016-10-30 17:06 UTC, bibaev commented on practice/src/main/java/homework/ftp/server/FtpServer.java
> +        System.err.println("Protocol error: unknown action with id = " + String.valueOf(actionId));
и тут тоже пофиксил

2016-10-30 17:06 UTC, bibaev commented on practice/src/main/java/homework/ftp/server/FtpServer.java
> +        continue;
теперь закрыли

2016-10-30 17:06 UTC, bibaev commented on practice/src/main/java/homework/ftp/server/FtpServer.java
> +        if(clientSocket.isClosed()) {
Думаю нет. Похоже, я в этом месте хотел написать:

```
if (socket.isClosed()) {
    break;
}
```

Но это лишнее, если кто-то и сделает socket.close() то выбросится исключение

2016-10-30 17:07 UTC, Roenke commented on practice/src/main/java/homework/ftp/server/Server.java
> +}
Эти интерфейсы задумывались для обработки исключений. А так, я согласен, что получилась избыточная иерархия

2016-10-30 17:07 UTC, Roenke commented on practice/src/main/java/homework/ftp/common/ProtocolDetail.java
> +}
да уж. Исправил :)

2016-10-30 17:08 UTC, Roenke commented on practice/src/main/java/homework/ftp/client/requests/GetFileRequest.java
> +      }
Согласен, теперь там largeCopy и проверка, что пришло столько данных сколько нужно

2016-10-30 17:08 UTC, Roenke commented on practice/build.gradle
>      mavenCentral()
это действительно так 👍

2016-10-31 15:04 UTC, sproshev commented
можно смотреть?

2016-10-31 18:06 UTC, Roenke commented
Ага

пн, 31 окт. 2016, 18:06 Semyon Proshev <notifications@github.com>:

> можно смотреть?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Roenke/java-autumn/pull/4#issuecomment-257318634>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AHQY1ym_OvAz8xWothZcvoHPhcxY8Fdxks5q5gOEgaJpZM4KRutw>
> .
>

2016-10-31 21:12 UTC, sproshev commented on practice/src/main/java/homework/ftp/server/FtpServer.java
> +        continue;
?

```
      } catch (IOException e) {
        System.err.println("Something went wrong. " + e.toString());
        continue;
      }
```

в этом месте сокет не закрывается

2016-10-31 21:18 UTC, sproshev commented
зачтено, 9

2016-11-01 08:52 UTC, merged